displayName=Mace Sound Swapper
author=touchtouch105
description=Makes maces sound beefier
tags=sound,swap,replace,effect,volume,inquistor,mace,inquistors
plugins=com.macesoundswapper.MaceSoundSwapperPlugin