displayName=Simple Sound Swapper
author=touchtouch105
description=Allows swapping of sounds based off sound ID
tags=sound,ID,swap,replace,effect,volume
plugins=com.simplesoundswapper.SimpleSoundSwapperPlugin